### ISSUE TITLE
dropdown 组件 bug

### ISSUE THREAD

**Issue by wfxs2012** [FriedRiceNoodles/banana-ui#121]
错误描述：  
使用  b-dropdown 组件 弹出菜单位置出现错误

代码如下：
```
 <b-dropdown trigger-action="click">
                    <b-button>Click me!</b-button>
                    <b-menu slot="drop" style="max-width: 200px;">
                        <b-menu-item>Option 1</b-menu-item>
                        <b-menu-item>Option 2</b-menu-item>
                        <b-menu-item>Option 3</b-menu-item>
                        <b-menu-item>Option 4</b-menu-item>
                        <b-menu-item>Option 5</b-menu-item>
                        <b-divider></b-divider>
                        <b-menu-item>Option A</b-menu-item>
                        <b-menu-item>Option B</b-menu-item>
                    </b-menu>
   </b-dropdown>
```

截图：
![image](https://github.com/FriedRiceNoodles/banana-ui/assets/108644586/c654700c-5768-46d1-a568-e0fb2888d2d5)

浏览器：chrome 版本 123.0.6312.106

pachage.json

```
 "dependencies": {
    "@banana-ui/banana": "^1.17.10",
    "@lit-labs/context": "^0.5.1",
    "@lit-labs/router": "^0.1.3",
    "@popperjs/core": "^2.11.8",
    "lit": "^3.1.2",
    "lucide": "^0.365.0",
    
  },
  "devDependencies": {
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "typescript": "^5.2.2",
    "vite": "^5.2.7"
  }

```

**Comment by FriedRiceNoodles** [comment]
似乎无法复现这个问题，可以麻烦提供更多的信息吗？感谢❥(^_-)

**Comment by FriedRiceNoodles** [comment]
尝试了一下在我的开发环境下没复现出来，待会我会试着把依赖项的版本锁定成你提供的版本号。
另外如果可以的话，或许能在codepen或[stackblitz](https://stackblitz.com/)提供一个可复现的链接吗。感谢♪(･ω･)ﾉ

**Comment by FriedRiceNoodles** [comment]
复现条件应该是，展开dropdown后浏览器窗口resize，这个问题应该是调用`floating-ui`的配置没有设置好。

**Comment by wfxs2012** [comment]
我写了个demo 但奇怪的是问题没有出现
https://stackblitz.com/edit/vitejs-vite-yqx1xm?file=src%2Fmy-element.ts

结构与demo中一样   渲染的区域就如下图
            
![image](https://github.com/FriedRiceNoodles/banana-ui/assets/108644586/c80a5f3b-9c8f-4c06-b452-329917c23765)



我的解决方案
```
 static styles = css`
      b-dropdown::part(drop) {
        position: fixed;
      }
`
```

所以我就很奇怪为什么demo中就没有这个问题

**Comment by FriedRiceNoodles** [comment]
> 我写了个demo 但奇怪的是问题没有出现 https://stackblitz.com/edit/vitejs-vite-yqx1xm?file=src%2Fmy-element.ts
> 
> 结构与demo中一样 渲染的区域就如下图
> 
> ![image](https://private-user-images.githubusercontent.com/108644586/320385209-c80a5f3b-9c8f-4c06-b452-329917c23765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjA1NTksIm5iZiI6MTcxMjU2MDI1OSwicGF0aCI6Ii8xMDg2NDQ1ODYvMzIwMzg1MjA5LWM4MGE1ZjNiLTljOGYtNGMwNi1iNDUyLTMyOTkxN2MyMzc2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwNzEwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjM0ODdhNzIzNjY3MGRmMTcyZDIxMDJkYzg0ZWNjMTgzYzgyMWJiMjYyYmI3MzU3ODc2OTU3MTNmZjc3NWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OqSKQ3pEJZUVfy450dKekNKa84ZO47TyFAynHC4j9-4)
> 
> 我的解决方案
> 
> ```
>  static styles = css`
>       b-dropdown::part(drop) {
>         position: fixed;
>       }
> `
> ```
> 
> 所以我就很奇怪为什么demo中就没有这个问题

如果触发条件是我说的那样，那这个问题在几个小时前发布的最新版本中已经被修复了。
