### ISSUE TITLE
能否提供px to rem的功能呢？

### ISSUE THREAD

**Issue by leevben** [FriedRiceNoodles/banana-ui#139]
我的使用场景是需要兼容多个尺寸的机器的，因此业务基本上都需要使用px to rem插件，但由于Web Components的特性，px to rem似乎并不能影响到Web Component内部的样式，因此能不能提供类似AntD的transform功能呢？感谢大佬！

**Comment by FriedRiceNoodles** [comment]
暂时没有这项计划哈，欢迎你提交相关pr
